version: '2.3'
services:
  database:
    image: mariadb:${TAG:-latest}
    container_name: innoacad_mariadb
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
  
  migrate:
    container_name: innoacad_migrate
    build:
      context: ./migrate
      dockerfile: ./Dockerfile
    depends_on:
      - database
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}

  api:
    container_name: innoacad_server
    build:
      context: ./api
      dockerfile: ./Dockerfile
    working_dir: /app/api
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - database
      - migrate
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./api:/app/api
